---
title: "Marginal and conditional probabilities"
output:
  html_document:
    df_print: paged
  word_document: default
---

## Sheep and horses in formal notation

Your first task is to figure out how the description of the problem can be translated into formal notation, which will then help you find a solution. The following example with sheep and horses will help you understand the notation you need.

In our example, we are interested in whether animals on a farm like apples. The animals at the farm are sheep and horses.

70 percent of the animals on the farm are sheep, and 30 percent are horses. So if we pick one random animal, and each animal has the same chance of being picked, the probability of picking a sheep is 0.7 and the probability of picking a horse is 0.3.

To write this in a more formal way, we say the event of randomly picking a sheep is A, and the event of randomly picking a horse is B. Then

$P(A)=0.7$

$P(B)=0.3$.

$P(A)$ is the *marginal probability* of picking a sheep, meaning that it is the probability of picking a sheep if you simply pick any animal from the farm.

Here comes some more information about the farm animals: 20 percent of the sheep like apples, and 80 percent of the horses like apples.

Another way to express the same information is this: Given that the randomly selected animal is a sheep, the probability that it likes apples is 0.2. Given that the animal is a horse, the probability that it likes apples is 0.8.

These are called *conditional probabilities*. To write them in formal notation, we let $Y$ be the event that an animal likes apples.

$P(Y|A)=0.2$

$P(Y|B)=0.8$

You can read the vertical line $|$ as "given", so $P(Y|A)=0.2$ reads "The probability of $Y$ given $A$ is 0.2". And in this context it means "Given that a randomly chosen animal on the farm is a sheep (A), the probability that it likes apples (Y) is 0.2".