---
title: "Sequences of independent events"
output:
  html_document:
    df_print: paged
  word_document: default
---

You have three events $A, B, C$ that can occur. The events are independent, which means that the probability that $A$ occurs is not affected by whether $B$ occurs, etc.

If you want to know the probability that all of $A$, $B$ and $C$ occur, you simply multiply the probabilities:

$P(A, B, C)=P(A)P(B)P(C)$

We could also have a sequence of trials with the same probability each time of a certain outcome. If you roll a fair die several times, then each time you have the probability $1/6$ of getting a six, so if $X_1$ is the outcome of one roll, then

$P(X_1=6)=\cfrac{1}{6}$

Each roll of the die is independent, which means that the next roll is not affected by the outcome of the last roll. Now, what is the probability of getting three sixes in a row? We have three independent events $X_1, X_2, X_3$, each with the probability of $1/6$ of occuring, so

$P(X_1=6, X_2=6, X_3=6)=P(X_1=6) \cdot P(X_2=6) \cdot P(X_2=6)= \cfrac{1}{6} \cdot \cfrac{1}{6} \cdot \cfrac{1}{6} = \cfrac{1}{216} \approx 0.0046$

Remember that this is only true when the events are independent.